version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    groups:
      microsoft-aspnetcore:
        patterns:
          - Microsoft.AspNetCore.*
      xunit:
        patterns:
          - xunit*
      open-telemetry:
        patterns:
          - OpenTelemetry*
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
